### ISSUE TITLE
Feature request: Add more GlInternalFormat enums

### ISSUE THREAD

**Issue by iMrShadow** [mcraiha/libktxsharp#3]
Hi! I am working on a texture converter, which extracts texture data from proprietary game files to DDS. I am planning to add KTX and KTX2 support, however, the games use ATC and PVRTC compression formats which this library [doesn't have](https://github.com/mcraiha/libktxsharp/blob/master/lib/KtxCommon.cs#L208).

Here's a [link](https://github.com/KhronosGroup/KTX-Software/blob/main/interface/java_binding/src/main/java/org/khronos/ktx/KtxInternalformat.java#L51) to all formats for reference. 

It would be great to add them, thanks

**Comment by mcraiha** [comment]
Do you have some sample texture files I could use for testing?

**Comment by iMrShadow** [comment]
These [samples](https://github.com/user-attachments/files/15806672/ATC_Samples.zip) are produced using AMD's Compressonator. They also support ATC formats for DDS containers, but they are not native to them and DirectXTex does not recognise them. 
As for PVRTC, I don't have any, unfortunately.

The enums would be just enough, so that I can identify the formats easier

**Comment by mcraiha** [comment]
I added the ATC ones
https://github.com/mcraiha/libktxsharp/commit/ff218f2ec2f0a297760bc560e43fedef0473b4c5

**Comment by iMrShadow** [comment]
Hello! Thanks for the additions 

Apologies for not replying earlier, the past week has been really busy

Here are some samples generated by PVRTexTool. There are 4 ktx textures named after their encoded formats. However, I didn't find any reliable texture viewer except for PVRTexTool. If you know any please let me know
[PVRTC.zip](https://github.com/user-attachments/files/15954259/PVRTC.zip)

**Comment by mcraiha** [comment]
I added the PVRTC ones
https://github.com/mcraiha/libktxsharp/commit/759db2ca0667fc7512d01ac2efc4b19c50856503

**Comment by iMrShadow** [comment]
Thank you very much!

I am closing the issue
