### ISSUE TITLE
stream does not have to be a new stream

### ISSUE THREAD

**Issue by zhouwenkan** [mcraiha/libktxsharp#4]
stream.Seek(12, SeekOrigin.Begin);

stream does not have to be a new stream. Supporting a stream that is partially read may be better. Otherwise we may have to create a new buffer.

**Comment by mcraiha** [comment]
I did a change for this
https://github.com/mcraiha/libktxsharp/commit/b1d80cc84a7a286949bcb3ffba45aedb04665528

**Comment by zhouwenkan** [comment]
Thanks a lot for the feature!
